version: '3.8'

services:
  postgres:
    env_file:
      - ../.env
    container_name: trading-db
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: simulated_trading_platform
      POSTGRES_USER: trading_user
      POSTGRES_PASSWORD: trading_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - trading_network
    restart: unless-stopped

  fastapi:
    env_file:
      - ../.env
    container_name: trading-api
    build:
      context: ../Backend/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - cpp-engine
    environment:
      DATABASE_URL: postgresql://trading_user:trading_password@postgres:5432/simulated_trading_platform
    volumes:
      - cpp_engine_shared:/shared
    networks:
      - trading_network
    restart: unless-stopped

  cpp-engine:
    env_file:
      - ../.env
    container_name: trading-engine
    build:
      context: ../Backend/cpp-engine
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://trading_user:trading_password@postgres:5432/trading_platform
    volumes:
      - cpp_engine_shared:/shared
    networks:
      - trading_network
    restart: unless-stopped
    command: >
      sh -c "
        ls -la / &&
        ls -la /app/build/ &&
        mkdir -p /shared &&
        ls -la /shared &&
        cp /app/build/trading_engine /shared/ &&
        chmod +x /shared/trading_engine &&
        echo 'C++ engine binary copied to /shared/trading_engine' &&
        ls -la /shared/ &&
        tail -f /dev/null
      "

  frontend:
    env_file:
      - ../.env
    container_name: trading-ui
    build:
      context: ../Frontend/trading-platform-ui
      dockerfile: Dockerfile
      target: production
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-http://localhost:8000}
    ports:
      - "80:80"
    depends_on:
      - fastapi
    networks:
      - trading_network
    restart: unless-stopped

volumes:
  postgres_data:
  cpp_engine_shared:

networks:
  trading_network:
    driver: bridge