version: '3.8'

services:
  postgres:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: trading_platform
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: dev_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database:/docker-entrypoint-initdb.d
    networks:
      - trading_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - trading_network

  fastapi:
    build:
      context: ./Backend/api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://trader:dev_password@postgres:5432/trading_platform
      REDIS_URL: redis://redis:6379
    volumes:
      - ./Backend/api:/app
    networks:
      - trading_network
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  cpp-engine:
    build:
      context: ./Backend/cpp-engine
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://trader:dev_password@postgres:5432/trading_platform
    volumes:
      - ./Backend/cpp-engine:/app
    networks:
      - trading_network

  frontend:
    build:
      context: ./Frontend/trading-platform-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fastapi
    volumes:
      - ./Frontend/trading-platform-ui:/app
      - /app/node_modules
    networks:
      - trading_network
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:
  redis_data:

networks:
  trading_network:
    driver: bridge